a New branch
TebohoRomeo/Covid-19 pull request #1
Opened 2020-07-01 14:00 UTC by TebohoRomeo

2020-07-01 14:16 UTC, TebohoRomeo commented
A covid 19 information pulled

2020-07-06 09:44 UTC, Dibwe243 requested changes
Hi Romeo,

Please create a proper Readme file. Could you also please create a pull request for the entire project I need to add my comment to it.

Thank you

2020-07-08 07:22 UTC, leanny01 requested changes

2020-07-08 07:22 UTC, leanny01 commented on README.md
>  In the project directory, you can run:
You have done well to add a description, there are few things missing though,  please see bellow suggestions
 It is recommended to guide the user step by step on how to run the app
```suggestion

1. move to the project directory within your terminal `cd  ~/Projecte_directory`
2. install dependencies ` npm run install`
3. start the app `npm run start `
```

Please be mindful of styling, feel free to google the internet for ideas.

2020-07-08 07:22 UTC, leanny01 commented on README.md
>  In the project directory, you can run:
1. move to the project directory within your terminal `cd  ~/Projecte_directory`
2. install dependencies ` npm run install`
3. start the app `npm run start `

2020-07-08 07:22 UTC, leanny01 commented on README.md
>  ## Available Scripts
This could be 
### Instalation instructions

2020-07-08 07:22 UTC, leanny01 commented on README.md
> -# Covid-19
Please ring back this tile 

#### Covid-19

2020-07-14 09:43 UTC, leanny01 approved these changes
Well done!

2020-07-14 09:52 UTC, merged